CC=g++

CFLAGS_DEBUG=-Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_EJUDGE_CLIENT_SIDE
CFLAGS_RELEASE=-DNDEBUG -O2

SOURCES=main.cpp user_menu.cpp solve_quad.cpp solve_linear.cpp get_input_double.cpp s_gets.cpp solve_quad_command_line.cpp cool_assert.cpp vibrant_print.cpp doublecmp.cpp unit_test.cpp answers_output.cpp command_line_io.cpp color_vfprintf.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=SquareSolver

CFLAGS = $(if $(release),$(CFLAGS_RELEASE),$(CFLAGS_DEBUG))

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) -c $(CFLAGS) $< -o $@


